### PR TITLE
Common texts

### PR DESCRIPTION
**Pull request by anermina**
Notes:
1. page with Foreword is not needed
2. Introduction should be after Summary and Keywords
3. Table of Contents is not needed
4. Normative references are rendered as 4th section
5. footer is not needed
6. ">" and "<" signs are not rendered well in Keywords

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thanks @anermina we need @opoudjis to comment here too since there are some ISO considerations.

**Comment by opoudjis** [comment]
@ronaldtse Reminder: please assign me PRs, rather than requesting reviews. I simply am not checking my notifications as frequently, whereas I notice assignments immediately on my project board.

**Comment by ronaldtse** [comment]
@opoudjis sure, it's all yours. Merge when ready.

**Comment by opoudjis** [comment]
I don't have enough context for this: is this intended to be a document that can generate both ITU and ISO output? If so, it certainly won't under Metanorma: the ISO foreword is missing (https://github.com/metanorma/mn-templates-iso/blob/master/international-standard/sections/00-foreword.adoc). The solution of shoving metadata into a main document table, instead of document attributes, per https://github.com/metanorma/mn-templates-itu/pull/12/files#diff-039f178f1a2197f8f1ed99a2604d9db8, is gob-smacking, but of course this is feeding into a manual process that is blissfully unaware of Metanorma anyway. 

The rest looks... well, plausible, but I think just perpetuating the current offline template for joint documents is counterproductive, and this needs to be discussed with ITU. Metanorma provides solutions to the challenge of joint documents that the current process does not: the same XML can be used to generate both a native ITU and a native ISO document, with some coordination, and I think that is far more useful as a future approach than populating the preface table for copy pasting into a Word document....

**Comment by opoudjis** [comment]
Oh, and until `:common-text-docnumber:` is implemented, this template won't work; but the same applies to all those templates you've added to the queue. Templating these is three months premature.

**Pull request merged**
